#!/bin/bash

set -e
set -u

case `(uname -s || echo unknown) 2>/dev/null` in
CYGWIN*)
	;;
*)
	echo "Unsupported platform"
	exit 1
	;;
esac

case `(uname -m || echo unknown) 2>/dev/null` in
i686)
	ARCH=x86
	;;
x86_64)
	ARCH=x86_64
	;;
*)
	echo "Unsupported CPU architecture"
	exit 1
	;;
esac

REPO=https://sourceforge.net/projects/virtualgl/files/cygwin/

mkdir -p $HOME/.vglrepo/$ARCH
echo Fetching setup.ini ...
wget -q $REPO/$ARCH/setup.ini -O $HOME/.vglrepo/$ARCH/setup.ini
RELEASES=`grep install: $HOME/.vglrepo/$ARCH/setup.ini | cut -f2 -d:`
if [ "$RELEASES" = "" ]; then
	echo ERROR: No releases available
	exit 1
fi
grep install: $HOME/.vglrepo/$ARCH/setup.ini | cut -f2 -d: | while read file size md5sum; do
	if [ -f $HOME/.vglrepo/$file ]; then
		MD5SUM=`md5sum -b $HOME/.vglrepo/$file | awk '{print $1}'`
		SIZE=`stat --printf="%s" $HOME/.vglrepo/$file`
		if [ "$SIZE" != "$size" -o "$MD5SUM" != "$md5sum" ]; then
			echo Fetching $file ...
			wget -q $REPO/$file -O $HOME/.vglrepo/$file
		fi
	else
		echo Fetching $file ...
		wget -q $REPO/$file -O $HOME/.vglrepo/$file
	fi
	MD5SUM=`md5sum -b $HOME/.vglrepo/$file | awk '{print $1}'`
	SIZE=`stat --printf="%s" $HOME/.vglrepo/$file`
	if [ "$SIZE" != "$size" ]; then
		echo "ERROR: size of $file ($SIZE) does not match the value in setup.ini ($size)"
		exit 1
	fi
	if [ "$MD5SUM" != "$md5sum" ]; then
		echo "ERROR: MD5 sum of $file ($MD5SUM) does not match the value in setup.ini ($md5sum)"
		exit 1
	fi
done

echo Fetching Cygwin setup ...
wget -q https://cygwin.com/setup-$ARCH.exe -O $HOME/.vglrepo/setup-$ARCH.exe
chmod +x $HOME/.vglrepo/setup-$ARCH.exe
echo Launching Cygwin setup ...
$HOME/.vglrepo/setup-$ARCH.exe -X -n -L -l `cygpath -w $HOME/.vglrepo` -P VirtualGL
